export let ru = {
        //auth
        your_email_not_confirmed: 'Ваш E-mail не подтвержен',
        sign_in: 'Войти',
        sign_up: 'Создать аккаунт',
        remember_me: 'Запомнить меня',
        forgot_password: 'Забыли пароль?',
        user_name: 'Имя пользователя',
        company_name: 'Название компании',
        password_confirmation: 'Подтвердите пароль',
        terms_accept_consent: 'Я принимаю условия <a href={href}>Пользовательского соглашения</a>',
        accept_personal_data_processing: 'Нажимая на кнопку, вы даете согласие на обработку персональных данных',
        terms_accept_consent_required: 'Необходимо Ваше согласие с условиями <a href={href}>Пользовательского соглашения</a>',
        already_signed_up: 'Уже есть аккаунт?',
        email_was_sent_on: 'Ссылка для сброса пароля была отправлена на:',
        error: 'Ошибка',
        login_or_password_incorrect: 'Логин или пароль введены неверно',
        to_home: 'На главную',

        //header -
        products: 'Товары',
        orders: 'Заказы',
        clients: 'Клиенты',
        suppliers: 'Поставщики',
        reports: 'Отчеты',
        account: 'Аккаунт',
        settings: 'Настройки',
        integrations: 'Интеграции',
        plan_ended_notification: 'Исчерпан лимит для: {value}',
        //modals (has items from below this block)
        tel: 'Тел.',
        title: 'Название',
        type: 'Тип',
        measurements: 'Единицы измерения',
        measurements_short: 'Ед. измерения',
        cancel: 'Отмена',
        shop: 'Канал продаж',
        shop_type: 'Тип канала продаж',
        order_date: 'Дата заказа',
        name: 'Имя',
        email: 'E-mail',
        password: 'Пароль',
        website: 'Web-сайт',
        site: 'Сайт',
        show_more: 'Показать еще',
        show_less: 'Скрыть',
        choose_an_option: 'Выберите опцию',
        
        //header popout
        my_profile: 'Мой профиль',
        account_settings: 'Настройки аккаунта',
        lock: 'Заблокировать',
        logout: 'Выйти',
        language_id: 'ID языка',
        enter_language_id: 'Введите ID языка',
        store_id: 'ID канала продаж',
        enter_store_id: 'Введите ID канала продаж',
        
        //sidebar
        menu_items_absent: 'Пункты меню отсутствуют',

        //products

        back: 'Назад',
        no_products: 'Товары отсутствуют',
        no_product_categories: 'У этого товара отсутствуют категории',
        no_product_prices: 'У этого товара отсутствуют цены',
        no_product_stores: 'У этого товара отсутствуют каналы продаж',
        no_product_suppliers: 'У этого товара отсутствуют поставщики',
        no_product_warehouses: 'У этого товара отсутствуют склады',
        no_product_custom_attributes: 'У этого товара отсутствуют пользовательские поля',
        no_customer_custom_attributes: 'У этого клиента отсутствуют пользовательские поля',
        no_sells_canals: 'Нет каналов продаж',
        product: 'Товар',
        product_name: 'Название товара',
        product_code: 'Код товара',
        category: 'Категория',
        subcategory: 'Подкатегория',
        categories: 'Категории',
        product_description: 'Описание товара',
        barcode: 'Штрихкод',
        on_receipt: 'На приемку',
        chosen: 'Выбрано',
        remove: 'Убрать',
        presume: 'Наименование',
        count: 'Количество',
        weight: 'Вес',
        width_height_deep: 'Ширина х Высота х Глубина',
        description: 'Описание',
        prices: 'Цены',
        price_type: 'Тип цены',
        price_type_id: 'ID типа цены',
        price_types: 'Типы цен',
        price: 'Цена',
        promo_price: 'Промо цена',
        supplier: 'Поставщик',
        string_number: 'Номер строки',
        upload_time: 'Дата загрузки',
        sale_price: 'Рекомендуемая цена',
        purchase_price: 'Закупочная цена',
        existence: 'Наличие',
        product_shop_id: 'ID товара в канале продаж',
        shop_article: 'Артикул для канала продаж',
        user_custom_fields: 'Пользовательские поля',
        field_name: 'Название поля',
        value: 'Значение',
        active: 'Активный',
        active_him: 'Активный',
        product_photos: 'Фото товара',
        choose_photo: 'Выбрать фото',
        choose: 'Выбрать',
        upload_image: 'Загрузить изображение',
        upload_images: 'Загрузить изображение(-ия)',
        image_link: 'Ссылка на изображение',
        straight: 'Напрямую',
        no_notifications: 'Нет уведомлений',
        clear_notifications: 'Очистить уведомления',
        press_here:'Нажмите здесь',
        to_go_to_import:'чтобы перейти в импорт',
        to_refresh_the_page:'чтобы обновить страницу',
        db_has_been_created_refresh_page:'База данных создана, обновите страницу',
        url: 'По URL',
        close: 'Закрыть',
        in_stock: 'В наличии',
        not_in_stock: 'Нет в наличии',
        units: 'шт.',
        unit: 'Ед.',
        image: 'Изображение',
        no_images: 'Нет изображений',
        no_image: 'Нет изображения',
        no_categories: 'Нет категорий',
        no_prices: 'Нет цен',
        no_price_types: 'Типы цен отсутствуют',
        no_suppliers: 'Нет поставщиков',
        stores: 'Каналы продаж',
        no_stores: 'Нет каналов продаж',
        warehouses_availability: 'Наличие по складам',
        whom_warehouses: 'скл',
        attr: 'пол.',
        no_attributes: 'Нет пользовательских полей',
        attributes: 'Пользовательские поля',
        sku_taken: 'Такой Артикул уже существует',
        sku: 'Артикул',
        open_image:'Открыть изображение',
        open: 'Открыть',
        enter_shop_url: 'Введите URL канала продаж',
        shop_url: 'URL канала продаж',
        add_product: 'Добавить товар',
        add_category: 'Добавить категорию',
        edit_category: 'Изменить категорию',
        add_price: 'Добавить цену',
        add_shop: 'Добавить канал продаж',
        add_user_custom_field: 'Добавить пользовательское поле',
        add_field: 'Добавить поле',
        product_detachment_success: 'Товар открелпен',
        product_detachment_error: 'Ошибка открепления товара',
        product_attachment: 'Вложенные товары',
        product_store_edit_success: 'Вы успешно отредактировали информацию о канале продаж в товаре',
        product_add_error: 'Ошибка добавления товара',
        product_add_supplier_success: 'Вы успешно добавили поставщика к этому товару',
        product_add_supplier_failure: 'Не удалось добавить поставщика к этому товару',
        product_detach_supplier_error: 'Ошибка открепления поставщика от товара',
        product_move_to_store_success: 'Операция переноса выбранных товаров в указанный канал продаж поставлена в очередь.',
        product_move_to_store_failure: 'Не удалось перенести выбранные товары в указанный канал продаж',
        move_products_to_store: 'Добавить в канал продаж',
        present: 'Есть',
        no: 'Нет',
        sure_to_delete_product: 'Вы действительно хотите удалить товар?',
        deleting_product_error: 'Ошибка при удалении товара',
        product_deleted: 'Товар удален',
        are_you_sure_you_want_regenerate_barcode: 'Вы уверены, что хотите сгенерировать штрихкод заново?',
        type_product_name: 'Введите имя товара',
        product_attachment_success: 'Товар успешно вложен',
        product_attachment_error: 'Ошибка при вложение товара',
        type_return_num: 'Введите номер возврата',

        //orders
        sales: 'Продажи',
        sales_complete: 'Завершенные продажи',
        
        recommended_price: 'Рекомендуемая цена',
        no_orders: 'Заказы отсутствуют',
        time_passed: 'Прошло',
        payment: 'Оплата',
        order: 'Заказ',
        manager: 'Менеджер',
        shipment_method: 'Способ доставки',
        shipment_cost: 'Стоимость доставки',
        comments: 'Коментарии',
        comment: 'Коментарий',
        order_products: 'Товары заказа',
        order_number: '№ заказа',
        return_number: '№ возврата',
        add_product_to_order: 'Добавить товар в заказ',
        add_product_to_order_active: 'Добавление товара в заказ',
        add_chosen_product: 'Добавить выбранный товар',
        product_edited: 'Товар отредактирован',
        products_cost: 'Стоимость товаров',
        products_shipment: 'Отгрузка товара',
        total: 'Итого',
        chosen_product: 'Выбранный товар',
        customer: 'Клиент',
        customer_info: 'Информация о клиенте',
        linked_orders: 'Связанные заказы',
        warehouse: 'Склад',
        warehouse_not_assigned: 'Укажите отгрузку',
        create_declaration: 'Создать декларацию',
        order_create_failure: 'Ошибка добавления заказа',
        order_create_success: 'Заказ создан!',
        leave_comment: 'Комментировать',
        order_delivery_cost_edit_success: 'Вы успешно изменили стоимость доставки заказа',
        order_payment_info_edit_success: 'Вы успешно изменили информацию об оплате заказа',
        order_customer_update_success: 'Вы успешно изменили клиента заказа',
        order_customer_update_failure: 'Ошибка изменения клиента заказа',
        order_required_fields_not_filled: 'Некоторые из обязательных полей для изменения статуса заказа не были заполнены',
        order_some_required_fields_not_filled: 'Для совершения данной операции, необходимо заполнить следующие поля заказа:',
        order_about_delivery: 'доставке',
        order_about_payment: 'оплате',
        order_about_customer: 'клиенте',
        order_about_manager: 'менеджере для обработки заказа',
        order_about_products: 'товарах или отгрузке товаров',
        order_fill_required_info_for_current_action: 'Пожалуйста, укажите данную информацию для совершения данной операции с заказом',
        order_fetch_all_products_failure: 'Ошибка при загрузке доступных товаров для заказа',
        order_fetch_product_sources_failure: 'Ошибка при загрузке информации по отгрузкам для товара',
        order_delivery_not_filled: 'В данном заказе не заполнены поля доставки. Пожалуйста, заполните их для изменения статуса заказа',
        order_payment_not_filled: 'В данном заказе не заполнены поля оплаты. Пожалуйста, заполните их для изменения статуса заказа',
        order_customer_not_filled: 'В данном заказе не указан клиент. Пожалуйста, укажите клиента для изменения статуса заказа',
        order_manager_not_filled: 'В данном заказе не указан менеджер для обработки заказа. Пожалуйста, укажите менеджера для изменения статуса заказа',
        order_status_edit_success: 'Вы успешно изменили статус заказа',
        order_status_edit_failure: 'Произошла ошибка при изменении статуса заказа',
        order_refreshing: 'Обновление заказа...',
        order_status_change_confirm: 'Вы действительно хотите изменить статус заказа на "{status}"?',
        order_status_change_confirm_zammler: 'Подтвердить создание приходного/расходного ордера в системе Zammler?',
        delivery_info: 'Информация о доставке',
        add_order: 'Добавить заказ',
        print_order: 'Распечатать заказ',
        order_no_products_available: 'Нет доступных товаров для выбранного канала продаж',
        order_no_products_available_instruction: 'Для того, чтобы добавить товары в этот заказ, Вам необходимо',
        order_no_products_supplier_available: 'Нет доступных товаров для выбранного поставщика',
        order_no_products_supplier_available_instruction: 'Для того, чтобы добавить товары в этот заказ, Вам необходимо',
        order_create_product_manually: 'Создать товар вручную',
        order_import_product: 'Импортировать товар',
        order_if_product_created_manually: 'Если товар создан вручную',
        order_attach_store_to_product: 'Закрепить конкретный канал продаж за нужным Вам товаром',
        order_no_product_sources_available: 'Нет доступных источников для данного заказа',
        order_import_stock: 'импортировать остатки',
        order_import_supplier_pricelist: 'импортировать прайс-лист поставщика',
        delivery_cost: 'Стоимость доставки',
        fill_from_order: 'Заполнить из заказа',
        fill_from_customer: 'Заполнить из клиента',
        order_comment: 'Комментарий к заказу',
        supplier_order_updated: 'Заказ поставщика изменен',
        supplier_order: 'Заказ поставщика',
        create_return_error: 'Ошибка при создании возврата',
        create_return_success: 'Возврат товаров из заказа создан',
        order_history: 'История заказа',
        changes: 'Изменения',
        date: 'Дата',
        order_info: 'Информация о заказе',
        no_order_history: 'У этого заказа нет истории',

        //orders return
        are_you_sure_you_want_create_return: 'Вы уверены, что хотите создать возврат',
        no_product_for_return: 'Нет товаров для вовзрата',
        add_return: 'Добавить возврат',
        no_returns: 'Нет возвратов',
        return_updated: 'Возврат изменен',
        create_return: 'Создать возврат',
        add_product_to_return: 'Добавить товар в возврат',
        return_added: 'Возврат добавлен',
        //customers
        add_client: 'Добавить клиента',
        no_clients: 'Клиент отсутствует',
        full_name: 'ФИО',
        age: 'Возраст',
        birth_date: 'Дата рождения',
        gender: 'Пол',
        male: 'Мужской',
        female: 'Женский',
        orders_count: 'Кол-во заказов',
        products_count: 'Кол-во товаров',
        total_orders: 'Сумма заказов',
        orders_history: 'История заказов',
        add_customer: 'Добавить клиента',
        external_customer_id: 'ID клиента в канале продаж',
        customer_delete_confirm: 'Вы действительно хотите удалить этого клиента?',
        customer_edit_success: 'Вы успешно отредактировали информацию о клиенте',
        customer_edit_failure: 'Ошибка при редактирования информации о клиенте',
        customer_delete_success: 'Вы успешно удалили клиента',
        customer_delete_failure: 'Ошибка удаления клиента',
        customer_image_update_failure: 'Ошибка изменения изображения пользователя',
        create_customer: 'Создать клиента',
        create_order: 'Создать заказ',
        customers: 'Клиенты',


        //custom attributes
        custom_attribute_names: 'Названия полей',
        custom_attribute_values: 'Значения полей',
        no_custom_attributes: 'Пользовательские атрибуты отсутствуют',
        no_this_custom_attribute_values: 'У этого пользовательского поля нет значений',
        editing_custom_attribute: 'Изменение поля...',
        add_custom_attribute_value: 'Добавить значение пользовательского поля',
        add_custom_attribute_value_success: 'Вы успешно добавили значение пользовательского поля',
        add_custom_attribute_value_failure: 'Ошибка при добавлении значения пользовательского поля',
        editing_custom_attribute_value: 'Изменение значения поля...',
        edit_custom_attribute_value_success: 'Вы успешно изменили значение пользовательского поля',
        edit_custom_attribute_value_failure: 'Ошибка изменения значения пользовательского поля',
        custom_attribute_name_edited: 'Название поля изменено!',
        error_editing_custom_attribute: 'Ошибка редактирования поля',

        //suppliers
        dropshipping: 'Дропшиппинг',
        info: 'Инфо',
        ownership_type: 'Форма собственности',
        stock_address: 'Адрес склада',
        email_for_orders: 'E-mail для заказов',
        director: 'Директор',
        supply: 'Поставки',
        messanger: 'Мессенджер',
        availability: 'Наличие',
        sizes_lwh: 'Размеры ДхШхВ, мм',
        weight_kg: 'Вес, кг',
        cost: 'Стоимость',
        tax_included: 'Включая НДС',
        currency: 'Валюта',
        purchasing: 'Закупочная',
        retail: 'Розничная',
        margin: 'Маржа',
        product_history: 'История товара',
        delivery_service: 'Служба доставки',
        city: 'Город',
        affiliate: 'Отделение',
        recievers_full_name: 'Ф.И.О получателя',
        all: 'Все',
        not_confirmed: 'Нет подтвержден',
        shipped: 'Отправлен',
        canceled: 'Отменен',
        supplier_delete_confirm: 'Вы действительно хотите удалить этого поставщика?',
        supplier_edit_success: 'Вы успешно изменили информацию о поставщике',
        supplier_edit_failure: 'Ошибка при редактирования информации о поставщике',
        suppliers_image_delete_success: 'Лого поставщика удалена',
        suppliers_image_delete_failure: 'Ошибка при удалении лого поставщика',
        supplier_delete_success: 'Вы успешно удалили поставщика',
        supplier_delete_failure: 'Ошибка удаления поставщика',
        set_to_confirm: 'На подтверждение',
        can_dropshipping: 'Использует дропшиппинг',
        use_rrc: 'Использует РРЦ',
        enter_supplier_email: 'Введите e-mail поставщика',

        add_supplier: 'Добавить поставщика',
        no_suppliers: 'Поставщики отсутствуют',
        internet_shops: 'Каналы продажи',

        //dropshipping
        notify_status: 'Статус оповещения',
        notified: 'Оповещен',
        not_notified: 'Не оповещен',
        notify: 'Оповестить',
        //report 

        //pricelists
        add_pricelist: 'Добавить прайслист',
        sheet_name: 'Имя таблицы',
        name_column: 'Колонка "Имя"',
        sku_column: 'Колонка "Артикул"',
        barcode_column: 'Колонка "Штрихкод"',
        sale_price_column: 'Колонка "Цена со скидкой"',
        purchase_price_column: 'Колонка "Закупочная цена"',
        qty_column: 'Колонка "Кол-во"',
        add_rows: 'Добавить строки',
        add_price_types_first: 'Для загрузки прайс-листа укажите типы цен, пожалуйста',
        add_warehouses_first: 'Для загрузки прайс-листа укажите склады, пожалуйста',
        pricelist: 'Прайс-лист',
        pricelist_id: 'ID прайс-листа',
        pricelists: 'Прайс-листы',
        pricelists_supplier: 'Прайс-листы поставщиков',
        load_pricelist: 'Загрузить прайс-лист',
        no_pricelists: 'Нет прайслистов',
        no_pricelists_of_this_type: 'Прайс-листы данного типа отсутствуют',
        stock_status: 'Статус наличия',
        pricelist_parameters: 'Параметры прайс-листа',
        pricelist_editing: 'Редактирование прайс-листа',
        pricelist_import_result: 'Результат импорта прайс-листа',
        pricelist_view: 'Просмотр прайс-листа',
        invalid_data_in_pricelist: 'Похоже, что в вашем прайс-листе отсутсвуют необходимые данные. Пожалуйста, проверьте целостность данных в первых 3 колонках таблицы.',
        invalid_data_in_pricelist_short: 'Похоже, что в вашем прайс-листе отсутсвуют необходимые данные. Пожалуйста, проверьте целостность данных.',
        pricelist_create_success: 'Вы успешно создали прайс-лист',
        pricelist_create_failure: 'Ошибка при импорте прайс-листа',
        rows_added: 'рядов добавлено в таблицу',
        no_pricelist_data: 'Нет данных об этом прайс-листе',
        replace_all_data: 'Установить "нет в наличии" на товары этого поставщика, которые не попали в прайс-лист',
        create_supplier_products: 'Установить связь с номенклатурой по артикулу',
        match_product: 'Найти соответствие товару',
        match_product_search_description: 'Введите название товара, который вы хотите связать с товаром из прайс-листа',
        match_product_success: 'Вы успешно установили соответствие для товара',
        match_product_failure: 'Не удалось установить соответствие для товара',
        create_products: 'Создать товары',
        create_products_success: 'Вы успешно создали товары',
        create_products_success_nothing_to_create: 'Товары уже были созданы',
        create_products_failure: 'Не удалось создать товары',
        product_already_matched_to_pricelist: 'Товар уже связан с прайс-листом',

        //novaposhta
        nova_poshta: 'Новая почта',
        np_api_token: 'API Токен Новой почты',
        areas: 'Области',
        cities: 'Города',
        settlements: 'Поселения',
        index: 'Индекс',
        work_time: 'Время работы',
        international_shipping: 'Международная доставка',
        no_contact_person: 'Нет контактных лиц',
        no_recipients: 'Нет получателей',
        no_senders: 'Нет отправителей',
        add_contact_person: 'Добавить контактное лицо',
        nova_poshta_api_key: 'API Новой Почты',
        recipient_added: 'Получатель добавлен',
        add_recipient: 'Добавить получателя',
        add_contragent: 'Добавить контрагента',
        add_contact_person: 'Добавить контактное лицо',
        add_address: 'Добавить адрес',
        general_info: 'Общая информация',
        counterparty_agents: 'Контрагенты',
        Sender: 'Отправитель',
        Recipient: 'Получатель',
        additional_parameters: 'Доп. параметры',
        backward_delivery: 'Обратная доставка',
        of_shipment: 'Отгрузки',
        auto_create: 'Создается автоматически',
        enter_service_type: 'Введите тип доставки',
        CounterpartyType: 'Тип контрагента',
        CounterpartyRef: 'Контрагент',
        FirstName: 'Имя',
        MiddleName: 'Отчество',
        LastName: 'Фамилия',
        Phone: 'Телефон',
        StreetRef: 'Улица',
        BuildingNumber: 'Номер дома',
        Flat: 'Квартира',
        Note: 'Коментарий',
        DeclarationNumber: 'Номер декларации',
        Sent: 'Отправлено',
        no_doc_number_yet: 'ТТН еще не создано',
        DateCreated: 'Дата создания',
        OrderNum: 'Номер заказа',
        order_num: 'Номер заказа',
        return_num: 'Номер возврата',
        Status: 'Статус',
        DateReceiving: 'Дата получения',
        ShippingCost: 'Стоимость доставки',
        ShipmentDate: 'Дата отправка',
        do_you_wanna_delete_recipient: 'Вы действительно хотите удалить получателя?',
        recipient_deleting_error: 'Ошибка при удаление получателя',
        no_declarations: 'Нет ТТН',        
        type_order_num: 'Введите номер заказа',
        declaration_added: 'Декларация добавлена',
        declaration_add_error: 'Ошибка в создании декларации',
        send_declaration: 'Отправить декларацию',
        declaration_sent_to_np: 'Декларация отправлена',
        ServiceType: 'Тип услуги',
        DeliveryType: 'Вид доставки',
        City: 'Город',
        Counterparty: 'Контрагент',
        Address: 'Адрес',
        Warehouse: 'Склад',
        ContactPerson: 'Контактное лицо',
        PayersType: 'Тип платильщика',
        PaymentForm: 'Форма оплаты',
        BackwardCargoType: 'Тип груза обратной доставки',
        CargoType: 'Тип груза',
        Weight: 'Вес',
        Volume: 'Объем',
        SpacesQty: 'Кол-во мест',
        Price: 'Цена',
        Amount: 'Сума',
        CargoDescription: 'Описание груза',
        PayersTypeRedelivery: 'Тип платильщика обратной доставки',
        Description: 'Описание',
        CityRef: 'Город',
        CityRef2: 'Город',
        OrganizationName: 'Имя организации',
        Email: 'Email',
        OwnershipForm: 'Форма собственности',
        declaration_edited: 'Декларация изменена',
        declaration_form: 'Форма декларации',
        save_and_send: 'Сохранить и отправить',
        shop_product_url: 'Ссылка на товар',
        sent: 'Отправлено',
        fill_fields_from_order: 'Заполнить поля из заказа',
        contact_person_add_error: 'Ошибка при добавлении контактного лица',
        recipient_add_error: 'Ошибка при добавлении получателя',
        address_add_error: 'Ошибка при добавлении адреса',


        //account
        account_logo_update_success: 'Вы успешно загрузили логотип для вашего аккаунта',
        account_logo_update_failure: 'Ошибка при загрузке логотипа для компании',
        account_logo_delete_success: 'Вы успешно удалили логотип вашего аккаунта',
        account_logo_delete_failure: 'Ошибка при удаления логотипа',
        attribute_set_id: 'ID набора полей в канале продаж',
        choose_image: 'Выберите картинку',
        users_management: 'Пользователи',


        //buttons
        save: 'Сохранить',
        edit: 'Редактировать',
        delete: 'Удалить',
        add_user: 'Добавить пользователя',
        restore: 'Восстановить',
        add_funds: 'Пополнить',
        send_question: 'Задать вопрос',
        add: 'Добавить',
        start_processing: 'Принять',
        ship: 'Отгрузить',
        delivered: 'Доставлен',
        put_aside: 'Отложить',
        complete: 'Завершить',
        cancel_infinitive: 'Отменить',
        
        //settings
        sells_canals: 'Каналы продаж',
        company: 'Компания',
        address: 'Адрес',
        contact_person: 'Контактное лицо',
        contact_phone: 'Контактный телефон',
        website: 'Сайт',
        phone_number: 'Телефон',
        tariff_plan: 'Тарифный план',
        token: 'Токен',
        enter_url: 'Введите URL',
        enter_token: 'Введите токен',
        consumer_key: 'Consumer key',
        enter_consumer_key: 'Введите consumer key',
        consumer_secret: 'Consumer secret',
        enter_consumer_secret: 'Введите consumer secret',
        export: 'Экспорт',
        add_export: 'Добавить экспорт',
        add_export_error: 'Ошибка при добавлении экспота',
        export_added: 'Экспорт добавлен',
        generate: 'Сгенерировать',
        export_deleted: 'Экспорт удален',
        export_deleting_error: 'Ошибка удаления экспорта',
        export_generated: 'Сгенерирован',
        export_generation_error: 'Ошиба генерации экспорта',
        delete_export_question: 'Удалить экспорт?',
        no_exports: 'Нет экспортов',
        VolumeGeneral: 'Объем',
        suppliers_list:'Список поставщиков',
        suppliers_prices:'Цены поставщиков',
        print_error: 'Ошибка <br> Для печати доступны только отправленные декларации',
        generated_date: 'Дата генерации',
        download: 'Скачать',
        processing_tree_order_changing: 'Изменение порядка категорий',

        //cancellation reasons
        add_order_cancellation_reason: 'Добавить причину отмены заказа',
        order_cancellation_reason: 'Причина отмены заказа',
        order_cancellation_reasons: 'Причины отмен заказов',
        order_cancellation_reason_edit_success: 'Вы успешно отредактировали причину отмены заказа',
        order_source_edit_success: 'Вы успешно отредактировали источник заказа',
        order_cancellation_reason_edit_failure: 'Не удалось отредактировать причину отмены заказа',
        order_source_edit_failure: 'Не удалось отредактировать источник заказа',
        order_cancellation_reason_delete_confirm: 'Вы действительно хотите удалить причину отмены заказа?',
        order_cancellation_reason_delete_failure: 'Не удалось удалить причину отмены заказа',
        order_source_delete_confirm: 'Не удалось удалить источник заказа',
        enter_order_cancellation_reason: 'Пожалуйста, введите причину отмены заказа',
        enter_default_cancellation_reason: 'Ввести из существующих причин',
        enter_custom_cancellation_reason: 'Ввести другую причину',
        no_cancellation_reasons: 'Нет причин отмен заказов',
        //management
        // user_management: 'Управление пользователями',
        users_data: 'Данные пользователя',
        permission_setting: 'Настройка прав',

        no_users: 'Пользователи отсутствуют',
        order_statuses: 'Статусы заказов',
        warehouse_statuses: 'Статусы складов',
        dropshipping_statuses: 'Статусы дропшиппинга',
        traffic_light_update_success: 'Вы успешно изменили параметры статуса',
        traffic_light_update_failure: 'Ошибка изменения параметров статуса',
        traffic_light_max_less_than_min: 'Значение этого поля должно быть больше, чем значение в <strong class="text-success">"зеленом"</strong> столбце',
        
        //backup
        // backup: 'Резервное копирование',
        backup_history: 'История бекапов',

        //imports
        product_imports_from_stores: 'Импорты товаров из каналов продаж',
        imports_from_stores: 'Импорты из каналов продаж',
        no_imports_yet: 'Еще не производилось ни одного импорта',
        import_added_to_queue: 'Данный импорт добавлен в очередь!',
        import_already_in_queue: 'Этот импорт уже в очереди',
        import_add_error: 'Ошибка при добавлении импорта в очередь',
        import_view_error: 'Ошибка при загрузке данных импорта',
        no_products_imported: 'Ни один товар не был импортирован',
        no_products_matched: 'Не найдено ни одного соответствия в товарах',
        no_products_validated: 'Ни один товар не прошел валидацию',
        no_import_errors: 'В этом импорте отсутствуют ошибки',
        import_found: 'Найдено',
        import_total: 'Всего',
        import_validated: 'Валидировано',
        import_validation_errors: 'Ошибки валидации',
        import_imported: 'Импортировано',
        import_skipped: 'Пропущено',
        import_errors: 'Ошибки импорта',
        import_matches: 'Найденные соответствия',
        import_result: 'Результат импорта',
        import_validated_items: 'Валидированные данные',
        import_create_success: 'Вы успешно добавили новый импорт',
        import_create_failure: 'Ошибка добавления импорта',
        import_complete_success: 'Вы успешно запустили процесс завершения импорта',
        import_complete_error: 'Ошибка завершения импорта',
        create_categories: 'Создавать категории',
        import_prices: 'Импортировать цены',
        import_price_id: 'Тип цены',
        import_stocks: 'Импортировать наличие',
        import_warehouse_id: 'Склад',
        import_without_confirmation: 'Импортировать без подтверждения',
        nothing_to_import: 'Нечего импортировать <br> (нет валидных товаров)',
        nothing_to_import_order: 'Нечего импортировать <br> (нет валидных заказов)',
        import_id: 'ID импорта',
        supplier_article: 'Артикул поставщика',
        //payments
        // payments: 'Платежи',
        amount: 'Сумма',
        payment_method: 'Способ оплаты',
        payment_status: 'Статус оплаты',
        payment_info: 'Информация об оплате',
        balance: 'Баланс',

        //support
        // support: 'Поддержка',
        question: 'Вопрос',

        //parameters
        // parameters: 'Параметры',
        orders_statuses: 'Статусы заказов',
        status: 'Статус',
        processing_time: 'Время обработки',
        color: 'Цвет',

        //integration
        // integration: 'Интеграция',
        api_access_keys: 'Ключи доступа API',
        api_key: 'API Ключ',
        activity: 'Активность',
        access_type: 'Тип доступа',
        allowed_methods: 'Разрешенные методы',
        
        //one sentence
        you_can_familiarize_with_api: 'С описанием методов API можно ознакомиться в',
        in_documentation: 'в документации',

        //prices types
        prices_types: 'Типы цен',
        add_prices_type: 'Добавить тип цен',
        no_prices_types: 'Типы цен отсутствуют',
        internet_stores: 'Каналы продаж',

        no_internet_stores: 'Каналы продаж отсутствуют',

        add_internet_store: 'Добавить канал продаж',
        //shops
        shops: 'Каналы продаж',
        store: 'Канал продаж',
        internet_shops: 'Каналы продаж',
        

        //setting
        // category
        products_categories_tree: 'Древо категорий товаров',
        add_category: 'Добавить категорию',
        category_name: 'Имя категории',
        enter_category_name: 'Введите имя категории',
        enter_attribute_set_id: 'Введите ID набора аттрибутов',

        //stores
        store_type: 'Тип канала продаж',
        store_api_check_cta: 'Проверьте настройки API интеграции канала продаж',
        store_api_works: 'Настройки API интеграции канала продаж были проверены. Ваш канал продаж успешно интегрирован с Uniorder',
        store_api_doesnt_work: 'Проверка API интеграции канала продаж выявила неисправности. Ваш Канал продаж не интегрирован с Uniorder',
        store_check_api_error: 'Ошибка проверки API интеграции канала продаж',
        store_checking_api: 'Идет проверка API интеграции канала продаж',
        supplier_whom: 'поставщика',

        //reports
        overdue_terms: 'Просроченные сроки',
        for_period: 'за период',
        by_every_status: 'по статусу',
        by_time_of_day: 'по времени суток',
        by_all_statuses: 'по всем статусам',
        orders_source: 'Источник заказов',
        for_months_weeks_days: 'по месяцу, неделе, дню',
        average_order_processing_time: 'Среднее время обработки заказов',
        orders_quantity: 'Количество заказов',
        products_quantity: "Количество товаров",
        in_orders: 'в заказах',
        in_order: 'в заказе',
        by_categories: 'по категориямы',
        Average: 'Среднее',
        quantity: 'количество',
        products_in_order_whom: 'товаров в заказе',     
        by_product_stock: 'По наличию товаров',
        by_suppliers: 'По поставщикам',
        by_groups: 'По группам',
        by_statuses: 'По статусам',
        customers_top: 'Топ клиентов',   
        top_selling_products: 'Топ продаваемых товаров',
        top_returns_products: 'Топ возвратов товара',
        expiring_products: 'Заканчивающиеся товары',
        top_suppliers_b2c_dropshipping: 'Топ Поставщиков - В2С заказы (дропшиппинг)',
        qty_suppliers_b2c_dropshipping: 'Количество В2С заказов по Поставщикам (дропшиппинг)',
        qty_suppliers_b2b_supplies: 'Количество В2B заказов по Поставщикам (поставки)',
        b2c_orders: 'B2C заказов',
        top_suppliers_b2b_orders: 'Топ Поставщиков - В2В заказы (поставки)',
        orders_cost_by_all_statuses: 'Стоимость заказов по всем статусам, тыс. грн.',
        orders_cost_by_status: 'Стоимость заказов по каждому статусу тыс.грн.',
        orders_cost_by_categories: 'Стоимость заказов по категориям тыс. грн.',
        top_selling_products_by_cost: 'ТОП продаж товаров по стоимости тыс. грн.',
        average_bill: 'Средний чек тыс. грн.',
        paid: 'Оплачено',
        not_paid: 'Не оплачено',
        average_processing_time_by_staff: 'Среднее время обработки заказов по Персоналу',
        overdue_orders_by_statuses: 'Просроченные заказы по статусам',
        overdue_ordrs_ratio: 'Соотношение просроченных заказов к общему количеству',
        'Заказ': 'Заказ',
        only_completed: 'Только завершенные',

        //warehouses
        stocks: 'Склады',
        warehouse: 'Склад',
        add_warehouse: 'Добавить склад',
        warehouses: 'Склады',
        accept: 'Принять',
        no_warehouses: 'Склады отсутствуют',
        can_be_pickup_point: 'Может быть точкой самовывоза',

        //warehouse shipments
        no_warehouse_receipts: 'Приемки отсутствуют',
        no_warehouse_shipments: 'Отгрузки отсутствуют',
        loading_warehouse_shipment: 'Загрузка данных по отгрузке...',
        editing_warehouse_shipment: 'Изменение данных по отгрузке...',
        editing_warehouse_shipment_status: 'Изменение статуса отгрузки...',
        warehouse_shipment_status: 'Статус отгрузки',
        edit_warehouse_shipment_success: 'Вы успешно отредактировали отгрузку со склада',

        //errors
        add_price_type_error: 'Ошибка при добавлении типа цены',
        product_detach_category_error: 'Ошибка при откреплении категории от товара',
        product_add_price_error: 'Ошибка при добавлении цены товару',
        product_detach_price_error: 'Ошибка при откреплении цены от товара',
        product_add_store_error: 'Ошибка при добавлении канала продаж к товару',
        product_cant_create_product_in_store: 'Невозможно создать товар в канале продаж',
        product_integration_api_error: 'Ошибка интеграции канала продаж <br> Перейти в настройки API?',
        product_detach_store_error: 'Ошибка при откреплении канала продаж от товара',
        product_edit_store_error: 'Ошибка при редактировании информации о канале продаж в товаре',
        product_add_warehouse_error: 'Ошибка при добавлении отгрузки по складу в товаре',
        product_edit_warehouse_error: 'Ошибка при редактировании отгрузки по складу в товаре',
        product_detach_warehouse_error: 'Ошибка при откреплении отгрузки от товара',
        order_payment_info_edit_error: 'Ошибка при редактировании информации об оплате заказа',
        warehouse_shipments_loading_error: 'Ошибка при загрузке данных по складам',
        warehouse_shipments_edit_error: 'Ошибка при редактировании данных по складам',
        multiple_warehouse_shipment_required: 'Необходимо выбрать отгрузки в таблице',
        show_user_error: 'Ошибка при загрузке информации пользователя',
        edit_user_error: 'Ошибка при редактировании пользователя',
        delete_user_error: 'Ошибка удаления пользователя',
        fetch_data_error: 'Ошибка при загрузке данных',
        delete_price_type_error: 'Ошибка при удалении типа цены',
        supplier_add_error: 'Ошибка при добавлении поставщика',
        supplier_info: 'Информация о поставщике',

        //general
        above: 'выше',
        confirm: 'Подтвердить',
        check: 'Проверить',
        data_replacement: 'Замена данных',
        date_created: 'Дата создания',
        date_updated: 'Дата последнего обновления',
        deletion: 'Удаление',
        import_id: 'ID импорта',
        image_delete_confirm: 'Вы действительно хотите удалить изображение?',
        image_delete_success: 'Изображение удалено!',
        image_delete_failure: 'Ошибка удаления изображения',
        supplier_product_name: 'Товар у поставщика',
        supplier_product_sku: 'SKU у поставщика',
        shop_sku: 'SKU канала продаж',
        shop_product_id: 'ID канала продаж',
        recipient: 'Получатель',
        recipient_phone: 'Телефон получателя',
        recipient_address: 'Адрес получателя',
        warehouses_list: 'Список складов',
        ttn: 'ТТН',
        print_declarations: 'Печать ТТН',
        SenderAddress:'Адрес отправителя',
        short_kg: 'кг.',
        short_grn: 'грн.',
        short_cubic_meters: 'м<sup>3</sup>',
        short_qty: 'шт.',
        no_info: 'Информация отсутствует',
        comment: 'Комментарий',
        change: 'Изменить',
        change_status: 'Изменить статус',
        search: 'Поиск',
        processing_request: 'Обработка запроса...',
        fetching_data: 'Загрузка данных...',
        uploading_image: 'Загружаем изображение...',
        image_upload_success: 'Вы успешно загрузили изображение',
        delivery: 'Доставка',
        skip: 'Пропустить',
        import: 'Импортировать',
        create: 'Создать',
        with_selected: 'С выбранными',
        finish: 'Завершить',
        start: 'Старт',
        view: 'Просмотр',
        refresh: 'Обновить',
        settings: 'Настройки',
        prices: 'Цены',
        measure_units: 'Ед. измерения',
        weight_units: 'Ед. измерения веса',
        volume_units: 'Ед. измерения размера',
        volume: 'Объем',
        not_found: 'Не найдено',
        reset: 'Сбросить',
        go_to_full_mode: 'Перейти в полный режим',
        create_demo_database: 'Создать базу данных',
        create_demo_database_success: 'База данных создана успешно!<br>Страница будет перезагружена в течении 10-15 секунд.',
        create_demo_database_failure: 'При обработке Вашего запроса на создание демо базы данных произошла ошибка. Пожалуйста, обратитесь в поддержку или попробуйте повторить попытку позже.',
        demo_mode: 'Демо-режим',
        demo_mode_explanation: 'Нажмите кнопку ниже для создания персональной базы данных и перехода в полноценный режим использования.',
        unprocessed: 'Необработано',
        toApi: 'Перейти к API',
        update: 'Обновить',
        or: 'или',
        necessary: 'Необходимо',
        from: 'от',
        to: 'до',
        hours_short: 'ч.',
        stock: 'Наличие',
        qty: 'Кол-во',
        search_not_found: 'По Вашему запросу результаты поиска отсутствуют',
        select_option: 'Выберите вариант',
        select_all: 'Выбрать все',
        deselect_all: 'Очистить',


        //dependency
        add_dependency_data: 'Добавить недостающие данные',
        dependency_data_missing: 'В вашем аккаунте отсутствуют некоторые необходимые данные. Пожалуйста, добавьте их для удобства Вашей дальнейшей работы с Uniorder',
        dependency_particular_data_missing: 'В вашем аккаунте отсутствуют <strong>"{entity_name}"</strong>. Пожалуйста, добавьте необходимые данные для удобства Вашей дальнейшей работы с Uniorder.',

        //summary field names
        field_name: 'Имя',
        field_organization: 'Организация',
        field_full_name: 'ФИО',
        field_status: 'Статус',
        field_type: 'Тип',
        field_sku: 'Код товара',
        field_weight: 'Вес',
        field_warehouse: 'Склад',
        field_unit: 'Ед. измерения',
        field_address: 'Адрес',
        field_type_ownership: 'Форма собственности',
        field_extra_phone: 'Телефон2',
        field_image: 'Изображение',
        field_sum_amount: 'Общая сума',
        field_amount: 'Цена',
        field_delivery_cost: 'Цена доставки',
        field_comment: 'Коментарий',
        field_order_date: 'Дата заказа',
        field_customer_name: 'Имя клиента',
        field_customer_phone: 'Телефон клиента',
        field_delivery_type: 'Тип доставки',
        field_order_num: 'Номер заказа',
        field_return_num: 'Номер возврата',
        field_payment_status_id: 'Статус оплаты',
        field_payment_type: 'Тип оплаты',
        field_payment_info: 'Информация об оплате',
        field_status_id: 'Статус',
        field_products: 'Товары',
        field_gender: 'Пол',
        field_phone: 'Телефон',
        field_birth_date: 'Дата рождения',
        field_email: 'E-mail',
        field_email_for_orders: 'E-mail для заказов',
        field_product_name: 'Имя товара',
        field_qty: 'Количество',
        field_price: 'Цена',
        field_quantity: 'Количество',
        field_description: 'Описание товара',
        field_volume: 'Размер',
        field_category: 'Категория',
        field_sales: 'Продажи',


        //shipment
        shipment: 'Отгрузка',
        shipment_from_warehouse: 'со склада',
        shipment_from_supplier: 'от поставщика',
        organization: 'Организация',
        //print
        print: 'Печать',
        print_action_infinitive: 'Распечатать',
        no_print_data: 'Отсутствуют данные для печати',
        print_data_loading_failure: 'При загрузке данных для печати произошла ошибка',

        //login modals
        reset_password: 'Сброс пароля',
        do_reset_password: 'Сбросить пароль',
        enter_new_password: 'Введите новый пароль',
        confirm_new_password: 'Подтвердите пароль',
        enter_account: 'Войти',

        forgot_password_qo: 'Забыли пароль?',
        enter_your_email_to_send_reset_link: 'Пожалуйста, введите свой эмейл, чтобы мы могли отправить вам ссылку для сброса пароля',




        //errors
        no_customer_for_this_id: 'По указанному ID нет клиента',
        no_supplier_for_this_id: 'По указанному ID нет поставщика',
        no_dropshipment_for_this_id: 'По указанному ID нет перевозки',
        image_to_large: 'Слишком большое изображение',
        image_not_uploaded: 'Изображение не загружено',

        //Table
        fields_configurator: 'Настройка полей',
        not_visible: 'Скрыто',
        visible: 'Показано',
        show: 'Показать',
        hide: 'Скрыть',
        to_preview: 'К предпросмотру',
        enter_text: 'Введите текст',
        ingtegration: 'Интеграция',
        delet_tab: 'Удалить вкладку',
        do_you_want_to_delete_tab: 'Удалить вкладку?',
        do_you_want_to_clear_tab: 'Очистить вкладку?',

        // integrations
        you_have_no_stores_this_type: 'У вас нет каналов продаж этого типа',
        zammler_api_key: 'API ключ Zammler',
        login: 'Логин',
        subject: 'Тема',
        list_id: 'ID списка',
        sender_email: 'E-mail отправителя',
        sender_name: 'Имя отправителя',
        we_are_working_on_it: 'Мы работаем над этим',
        your_account_is_not_active: 'Ваш аккаунт не активен. Ожидайте подтверждения!',

        select_account_type: 'Выберите тип аккаунта',
        go_to_demo_account: 'Демо аккаунт',
        go_to_real_account: 'Реальный аккаунт',
        config_master_heading: 'Мастер подключения',
        step: 'ШАГ',
        congratulations: 'Поздравляем',
        next: 'Далее',
        hide_window: 'Свернуть',
        welcome: 'Добро пожаловать!',
        demo_mode: 'Демо-режим',
        do_you_want_to_quit_from_demo: 'Выйти из ДЕМО-режима и создать свой аккаунт?',
        you_cant_go_back_to_demo: 'После нажатия кнопки Вы не сможете вернуться в ДЕМО-режим',
        event_name: 'Событие',
        message: 'Сообщение',
        subject: 'Тема',
        event__sms__order_status: 'Статус заказа',
        event__sms__new_order: 'Новый заказ',
        event__sms__order_in_progress: 'Заказ в обработке',
        event__sms__order_shipment: 'Заказ готовится к отправке',
        event__sms__order_shipped: 'Заказ отправлен',
        event__sms__order_delivered: 'Заказ доставлен',
        event__sms__order_finished: 'Заказ окончен',
        event__sms__order_deferred: 'Заказ отсрочен',
        event__sms__order_canceled: 'Заказ отменен',
        event__sms__order_deleted: 'Заказ удален',
        event__email__order_status: 'Статус заказа',
        event__email__new_order: 'Новый заказ',
        event__email__order_in_progress: 'Заказ в обработке',
        event__email__order_shipment: 'Заказ готовится к отправке',
        event__email__order_shipped: 'Заказ отправлен',
        event__email__order_delivered: 'Заказ доставлен',
        event__email__order_finished: 'Заказ окончен',
        event__email__order_deferred: 'Заказ отсрочен',
        event__email__order_canceled: 'Заказ отменен',
        event__email__order_deleted: 'Заказ удален',
        config_master: 'Мастер',
        documentation: 'Документация',
        password_changed_ok: 'Пароль изменен!',
        token_is_not_valid: 'Не правильный токен!',

        send: 'Отправить',
        tech_support: 'Тех. поддержка',
        priority: 'Приоритет',
        attachment: 'Приложение',
        choose_a_file: 'Выберите файл',
        your_ticket_success: 'Сообщение отправлено <br> Ожидайте ответа Тех. поддержки!',
        your_ticket_failure: 'Ошибка при создании тикета',
        your_balance: 'Ваш баланс',
        your_plan: 'Тарифный план',
        change_plan: 'Сменить тарифный план',
        fill_balance: 'Пополнить баланс',
        next_write_off: 'Следующие списание',
        add_funds: 'Добавить средства',
        amount_to_add: 'Сумма',
        open_ticket: 'Открыть тикет',
        ticket_history: 'История тикета',
        reply: 'Ответить',
        text: 'Текст',
        you: 'Вы',
        support: 'Поддержка',
        tokens_refreshed: 'API ключи сохранены!',
        tokens_refresh_error: 'Ошибка при сохранении API ключей!',

        //phone
        phone_call: 'Звонок',
        mongodb_uri: 'MONGO URI',

        password_confirm: 'Подвердите пароль',
        call_history: 'История звонков',
        no_calls: 'Нет звонков',
        call_customer: 'Позвонить клиенту',
        operator_number: 'Внутренний номер оператора',
        there_are_duplicated_sku: 'Следующие Артикулы уже существуют',
        were_created: 'Создано',
        entity_too_large: 'Размер файла слишком большой',
        you_cannot_upload_this_files: 'Вы не можете загружать файлы такого формата',
        price_type_ids: 'Типы цен',
        export_excel: 'Экспортировать в Excel',
        delete_tab: 'Удалить вкладку',
        field_chooser_master: 'Мастер настройки полей',
        attached_to_product: 'Вложенный',
        company_logo: 'Лого компании',
        no_transaction: 'Нет транзакций',
        to_go_to_balance: 'чтобы перейти в баланс',
        balance_was_filled: 'Баланс пополнен!',
        balance_fill_error: 'Ошибка при пополнении баланса!',
        balance_fill_failure: 'Ошибка при пополнении баланса!',
        stores_list: 'Список каналов продаж',
        refresh_import: 'Обновить импорт',
        declaration_sent: 'Декларация отправлена',
        add_order_order_source: 'Добавить источник заказа',
        order_order_sources: 'Источники заказа',
        no_order_sources: 'Нет источников заказа',
        order_source: 'Источник заказа',
        imported_items: 'Успешно импортировано',
        no_items_imported: 'Пусто',
        default_settings: 'Настройки по умолчанию',
        declaration_defaults_set: 'Настройки по умолчанию сохранены',
        no_currencies: 'Нет валют',
        add_currency_error: 'Ошибка при добавлении валюты',
        currencies: 'Валюты',
        link: 'Ссылка',
        currency: 'Валюта',
        choose_file: 'Выберите файл',
        use_as_default: 'Использовать как основную',
};